apiVersion: v1
kind: PersistentVolume
metadata:
  name: fl-volume
spec:
  storageClassName: local-storage
  volumeMode: Filesystem
  capacity:
    storage: 120Gi
  local:
    path: /mnt/local-storage/pv1
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteMany
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - "22273"